import pandas as pd

# Load the existing Spotify data
import os

# Get the current directory of the script
current_directory = os.path.dirname(__file__)

# Concatenate the directory path and the file name
file_path = os.path.join(current_directory, 'spotify-2023.csv')

spotify_df = pd.read_csv(file_path, encoding='latin1')

# Create a dictionary with track names and their respective genres
genre_dict = {   
        "Que Vuelvas": "Romantic", 
    "Jhoome Jo Pathaan": "Pop", 
    "QUEMA": "Pop", "Gol Bolinha", 
    "Gol Quadrado 2": "Hip-Hop",
    "Overdrive": "Pop", 
    "S91": "Hip-Hop", 
    "Rush": "Pop", 
    "Danger (Spider) (Offset & JID)": "Hip-Hop",
    "New Jeans": "Pop", 
    "Better Than Revenge (Taylor's Version)": "Pop",
    "What Was I Made For? [From The Motion Picture 'Barbie']": "Pop", 
    "Mi Bello Angel": "Romantic",
    "Phantom Regret by Jim": "Rock", 
    "Devil Don’t": "Rock",
    "Link Up (Metro Boomin & Don Toliver, Wizkid feat. BEAM & Toian) - Spider-Verse Remix (Spider-Man: Across the Spider-Verse)": "Hip-Hop",
    "Mother I Sober (feat. Beth Gibbons of Portishead)": "Hip-Hop", 
    "Born With A Beer In My Hand": "Hip-Hop",
    "Don't ever say love me (feat. RM of BTS)": "Hip-Hop", 
    "Mine (Taylor's Version)": "Pop",
    "Savior - Interlude": "Rock", 
    "All The Way Live (Spider-Man: Across the Spider-Verse) (Metro Boomin & Future, Lil Uzi Vert)": "Hip-Hop",
    "Every Angel is Terrifying": "Rock", 
    "Auntie Diaries": "Hip-Hop", 
    "Still With You": "Romantic",
    "LAGUNAS": "Pop", 
    "Back To December (Taylor's Version)": "Romantic", 
    "Enchanted (Taylor's Version)": "Romantic",
    "Hummingbird (Metro Boomin & James Blake)": "Hip-Hop", 
    "Novidade na": "Pop", "Curtains": "Pop",
    "Rich - Interlude": "Hip-Hop", 
    "A Tale By Quincy": "Rock", "Crown": "Pop",
    "Piñman De": "Pop", 
    "CORAZn VA": "Pop", 
    "Stand By Me (feat. Morgan Wallen)": "Romantic",
    "Karma (feat. Ice Spice)": "Hip-Hop", 
    "XQ Te Pones As": "Hip-Hop", 
    "Cheques": "Hip-Hop", 
    "Too Late": "Hip-Hop",
    "Worst Day": "Hip-Hop", 
    "Mejor Que Yo": "Hip-Hop", 
    "Far": "Hip-Hop", 
    "Lilith (feat. SUGA of BTS) (Diablo IV Anthem)": "Hip-Hop", 
    "I Can See You (Taylor's Version) (From The Vault)": "Pop",
    "TULUM": "Pop", 
    "HAPPY": "Pop", 
    "Mirror": "Pop", 
    "Stefania (Kalush Orchestra)": "Pop", 
    "Still Life": "Pop",
    "Dawn FM": "Pop", 
    "Lady Mi Amor": "Pop", 
    "Tere Vaaste (From 'Zara Hatke Zara Bachke')": "Romantic",
    "BABY HELLO": "Pop", 
    "SPACE MAN": "Pop", 
    "25k jacket (feat. Lil Baby)": "Hip-Hop", 
    "LUNA": "Pop",
    "98 Braves": "Hip-Hop", 
    "Conceited": "Hip-Hop", 
    "AMERICA HAS A PROBLEM (feat. Kendrick Lamar)": "Hip-Hop",
    "Smoking on my Ex Pack": "Hip-Hop", 
    "POLARIS - Remix": "Pop", 
    "(It Goes Like) Nanana - Edit": "Pop",
    "69": "Hip-Hop", 
    "MONTAGEM - FR PUNK": "Pop", 
    "Columbia": "Pop", 
    "Super Shy": "Pop", 
    "SORRY NOT SORRY": "Pop",
    "Mr. Morale": "Rock", 
    "Man Made A Bar (feat. Eric Church)": "Rock", 
    "Snow On The Beach (feat. More Lana Del Rey)": "Romantic",
    "thought i was playing": "Hip-Hop", 
    "Mami Chula": "Hip-Hop", 
    "MOJABI GHOST": "Rock", 
    "Worldwide Steppers": "Hip-Hop",
    "Notice Me": "Hip-Hop", 
    "Don't Break My": "Pop", 
    "Phir Aur Kya Chahiye (From 'Zara Hatke Zara Bachke')": "Romantic",
    "Bussin": "Hip-Hop", 
    "Gospel (with Eminem)": "Hip-Hop", 
    "Barbie World (with Aqua) [From Barbie The Album]": "Pop",
    "Gone Girl": "Pop", 
    "S-Class": "Pop", 
    "SloMo": "Pop", 
    "Rauw Alejandro: Bzrp Music Sessions, Vol. 56": "Pop",
    "VOID": "Pop", 
    "F2F": "Pop", 
    "Peaches (from The Super Mario Bros. Movie)": "Pop", 
    "Hits Different": "Pop",
    "We Cry Together": "Hip-Hop", 
    "Lovezinho": "Romantic", 
    "Self Love (Spider-Man: Across the Spider-Verse) (Metro Boomin & Coi Leray)": "Pop",
    "Obsessed": "Pop", 
    "The Rumbling (TV Size)": "Rock", 
    "Con La Brisa": "Pop", 
    "The Heart Part 5": "Hip-Hop",
    "Carto B": "Pop", 
    "A Veces (feat. Feid)": "Hip-Hop", 
    "SOS": "Pop",
        "Starry Eyes": "Pop",
    "psychofreak (feat. WILLOW)": "Pop",
    "Bite Me": "Pop",
    "Purple Hearts": "Romantic",
    "Shoong! (feat. LISA of BLACKPINK)": "Romantic",
    "Conexões de Máfia (feat. Rich)": "Hip-Hop",
    "Primera Cita": "Romantic",
    "Blessed-Cursed": "Pop",
    "I Know - PR1SVX Edit": "Pop",
    "On Time (with John Legend)": "Pop",
    "SABOR FRESA": "Pop",
    "Rumble": "Hip-Hop",
    "Born Singer": "Hip-Hop",
    "DOGTOOTH": "Rock",
    "Novo Balanço": "Pop",
    "Do We Have A Problem?": "Hip-Hop",
    "Red Ruby Da Sleeze": "Hip-Hop",
    "I Wrote The Book": "Rock",
    "Bye Bye": "Hip-Hop",
    "California Breeze": "Hip-Hop",
    "Hot Shit (feat. Ye & Lil Durk)": "Hip-Hop",
    "Savior": "Rock",
    "LADY GAGA": "Hip-Hop",
    "Annihilate (Spider-Man: Across the Spider-Verse) (Metro Boomin & Swae Lee, Lil Wayne, Offset)": "Hip-Hop",
    "Special": "Hip-Hop",
    "Here We Go Again (feat. Tyler, the Creator)": "Rock",
    "Ain't Tha": "Hip-Hop",
    "Chance": "Hip-Hop",
    "Abcdario": "Hip-Hop",
    "Agudo Mági": "Hip-Hop",
    "VAGABUNDO": "Hip-Hop",
    "Super": "Hip-Hop",
    "My Mind & Me": "Romantic",
    "I Heard You're Married (feat. Lil Wayne)": "Pop",
    "So Good": "Pop",
    "UNFORGIVEN (feat. Nile Rodgers)": "Pop",
    "BackOutsideBoyz": "Hip-Hop",
    "PERO TÍ": "Hip-Hop",
    "Sem Aliança no": "Hip-Hop",
    "Used (feat. Don Toliver)": "Hip-Hop",
    "Am I Dreaming (Metro Boomin & A$AP Rocky, Roisee)": "Hip-Hop",
    "Residente: Bzrp Music Sessions, Vol. 49": "Hip-Hop",
    "Bye": "Hip-Hop",
    "What It Is (Solo Version)": "Hip-Hop",
    "fukumean": "Hip-Hop",
    "Everything I Love": "Rock",
    "People Pt.2 (feat. IU)": "Pop",
    "Alone": "Hip-Hop",
    "Double Fantasy (with Future)": "Pop",
    "Queencard": "Pop",
    "Come Back Home - From 'Purple Hearts'": "Romantic",
    "Seek & Destroy": "Hip-Hop",
    "Arcángel: Bzrp Music Sessions, Vol. 54": "Hip-Hop",
    "Best Friends": "Hip-Hop",
    "Right On": "Pop",
    "Cupid – Twin Ver. (FIFTY FIFTY) – Special Version": "Pop",
    "I'm Not Here To Make Friends": "Pop",
    "Princess Diana (with Nicki Minaj)": "Pop",
    "Private Landing (feat. Justin Bieber & Future)": "Pop",
    "Broke Boys": "Hip-Hop",
    "Honest (feat. Don Toliver)": "Pop",
    "Sigue": "Pop",
    "City of Gods": "Hip-Hop",
    "Sugar Rush Ride": "Pop",
    "El Cielo": "Hip-Hop",
    "Thinking with My Dick": "Hip-Hop",
    "Calling (Spider-Man: Across the Spider-Verse) (Metro Boomin & Swae Lee, NAV, feat. A Boogie Wit da Hoodie)": "Hip-Hop",
    "Ghost in the Machine (feat. Phoebe Bridgers)": "Rock",
    "Raindrops (Insane) [with Travis Scott]": "Hip-Hop",
    "Love Language": "Pop",
    "Tí": "Hip-Hop",
    "Privileged Rappers": "Hip-Hop",
    "Area Codes": "Hip-Hop",
    "For Youth": "Hip-Hop",
    "Poland": "Hip-Hop",
    "Popular (with Playboi Carti & Madonna) - The Idol Vol. 1 (Music from the HBO Original Series)": "Pop",
    "Tubarão Te Amo": "Hip-Hop",
    "Dijeron Que No La Iba Lograr": "Hip-Hop",
    "on the street (with J. Cole)": "Hip-Hop",
    "REMIX EXCLUSIVO": "Hip-Hop",
    "Never Felt So Alone": "Hip-Hop",
    "Me Arrepentí": "Hip-Hop",
    "Take Two": "Hip-Hop",
    "Haegeum": "Hip-Hop",
    "How Do I Make You Love Me?": "Rock",
    "Nobody Like U - From 'Turning Red'": "Pop",
    "I Tried to Tell Y'all": "Hip-Hop",
    "La Loto": "Hip-Hop",
    "Bigger Than The Whole Sky": "Pop",
    "I'm Tired - From 'Euphoria' An Original HBO Series": "Rock",
    "Hey, Mickey!": "Pop",
    "Los del Espacio": "Hip-Hop",
    "Acróstico": "Hip-Hop",
    "I AM": "Hip-Hop",
    "Silent Hill": "Rock",
        "Stay With Me (with Justin Timberlake, Halsey, & Pharrell)": "Pop",
    "Miserable Man": "Rock",
    "LLYLM": "Hip-Hop",
    "Thinkin' B": "Pop",
    "Count Me Out": "Hip-Hop",
    "Soy El Unico": "Romantic",
    "Las Morras": "Hip-Hop",
    "Deck The Hall - Remastered 1999": "Hip-Hop",
    "Father Time (feat. Sampha)": "Rock",
    "Dance The Night (From Barbie The Album)": "Pop",
    "Say Yes To Heaven": "Pop",
    "Baile no Morro": "Hip-Hop",
    "Layla": "Pop",
    "Take My Breath": "Pop",
    "die first": "Pop",
    "This Love (Taylor’s Version)": "Pop",
    "LALA": "Pop",
    "Angel Pt 1 (feat. Jimin of BTS, JVKE & Muni Long)": "Pop",
    "En La De Ella": "Hip-Hop",
    "TRUSTFALL": "Pop",
    "Zona De Perigo": "Hip-Hop",
    "Brividi": "Pop",
    "O.O": "Hip-Hop",
    "Wild Flower (with youjeen)": "Rock",
    "Merry Christmas": "Pop",
    "Cash In Cash Out": "Rock",
    "Antidepresan": "Rock",
    "ZOOM": "Rock",
    "Boyfriends": "Pop",
    "Komang": "Hip-Hop",
    "Nos Comemos (feat. Ozuna)": "Pop",
    "Seu Brilho Sumiu - Ao Vivo": "Hip-Hop",
    "Fim de Semana no Rio": "Hip-Hop",
    "Cupid": "Pop",
    "Apna Bana Le (From 'Bhediya')": "Romantic",
    "vampire": "Pop",
    "Besharam Rang (From 'Pathaan')": "Hip-Hop",
    "I Really Want to Stay at Your House": "Romantic",
    "Seven (feat. Latto) (Explicit Ver.)": "Pop",
    "Circo Loco": "Hip-Hop",
    "Un Finde | CROSSOVER #2": "Hip-Hop",
    "212": "Hip-Hop",
    "All My Life (feat. J. Cole)": "Hip-Hop",
    "Heaven": "Pop",
    "Oi Balde - Ao Vivo": "Hip-Hop",
    "Bamba (feat. Aitch & BIA)": "Hip-Hop",
    "That's Hilarious": "Pop",
    "Mas Rica Que Ayer": "Hip-Hop",
    "The Joker And The Queen (feat. Taylor Swift)": "Romantic",
    "Di Que Si": "Hip-Hop",
    "Love Again": "Pop",
    "Talk": "Hip-Hop",
    "One Thing At A Time": "Hip-Hop",
    "Tormenta (feat. Bad Bunny)": "Hip-Hop",
    "Dua Lipa": "Pop",
    "VIBE (feat. Jimin of BTS)": "Pop",
    "Freaky Deaky": "Pop",
    "AMARGURA": "Hip-Hop",
    "Erro Gostoso - Ao Vivo": "Hip-Hop",
    "Malvada": "Hip-Hop",
    "Miss You": "Pop",
    "What Else Can I Do?": "Pop",
    "Major Distribution": "Rock",
    "Open Arms (feat. Travis Scott)": "Rock",
    "MORE": "Rock",
    "Malas Decisiones": "Hip-Hop",
    "Boy's a liar Pt. 2": "Pop",
    "Boy's a liar": "Pop",
    "Pope Is a Rockstar": "Pop",
    "Kahani Suno 2.0": "Pop",
    "United In Grief": "Hip-Hop",
    "Fast Car": "Pop",
    "Antes de Perderte": "Hip-Hop",
    "RUMBATÓN": "Hip-Hop",
    "Igualito a Mi Apá": "Hip-Hop",
    "BABY OTAKU": "Hip-Hop",
    "Beautiful Girl": "Romantic",
    "Die Young (feat. 347aidan)": "Hip-Hop",
    "Chanel": "Hip-Hop",
    "Shorty Party": "Hip-Hop",
    "Blind": "Hip-Hop",
    "Paulo Londra: Bzrp Music Sessions, Vol. 23": "Hip-Hop",
    "En El Radio Un Cochinero": "Hip-Hop",
    "Makeba": "Hip-Hop",
    "If We Ever Broke Up": "Pop",
    "Sial": "Hip-Hop",
    "Dos Oruguitas": "Romantic",
    "Set Me Free Pt.2": "Pop",
    "Gatita": "Hip-Hop",
    "On BS": "Hip-Hop",
    "Nxde": "Pop",
    "STAYING ALIVE (feat. Drake & Lil Baby)": "Hip-Hop",
    "ALIEN SUPERSTAR": "Hip-Hop",
    "Chemical": "Pop",
    "Like Crazy (English Version)": "Pop",
    "Rich Spirit": "Hip-Hop",
    "Evoque Prata": "Hip-Hop",
    "Search & Rescue": "Rock",
    "WANDA": "Hip-Hop", 
        "Ai Preto": "Hip-Hop",
    "sentaDONA (Remix) s2": "Hip-Hop",
    "Celestial": "Romantic",
    "TQM": "Hip-Hop",
    "Sí": "Hip-Hop",
    "Would've, Could've, Should've": "Romantic",
    "Baby Don't Hurt Me": "Pop",
    "Si Quieren Frontear": "Hip-Hop",
    "Jingle Bells - Remastered 1999": "Pop",
    "Si Te La Encuentras Por Ahí": "Hip-Hop",
    "Tak Segampang Itu": "Hip-Hop",
    "You Make It Feel Like Christmas (feat. Blake Shelton)": "Romantic",
    "Hrs and Hrs": "Romantic",
    "The Great War": "Romantic",
    "Shut up My Moms Calling - (Sped Up)": "Rock",
    "DARARI": "Hip-Hop",
    "295": "Hip-Hop",
    "Sprinter": "Hip-Hop",
    "Escapism. - Sped Up": "Hip-Hop",
    "TUS LÁGRIMAS": "Hip-Hop",
    "Good Looking": "Rock",
    "Tak Ingin Usai": "Hip-Hop",
    "Flowers": "Romantic",
    "The Family Madrigal": "Romantic",
    "GIVENCHY": "Hip-Hop",
    "All Of The Girls You Loved Before": "Romantic",
    "Prohibidox": "Hip-Hop",
    "Cigarettes": "Hip-Hop",
    "10 Things I Hate About You": "Rock",
    "Sweet Nothing": "Romantic",
    "Labyrinth": "Romantic",
    "Casei Com a Putaria": "Hip-Hop",
    "Daydreaming": "Romantic",
    "Vampiro": "Hip-Hop",
    "Frágil (feat. Grupo Frontera)": "Hip-Hop",
    "Cinema": "Hip-Hop",
    "Talk that Talk": "Hip-Hop",
    "Slut Me Out": "Hip-Hop",
    "Potion (with Dua Lipa & Young Thug)": "Hip-Hop",
    "In My Head": "Rock",
    "Pussy & Millions (feat. Travis Scott)": "Hip-Hop",
    "Sticky": "Rock",
    "Pipoco": "Hip-Hop",
    "La Bebe": "Hip-Hop",
    "Nail Tech": "Hip-Hop",
    "True Love": "Hip-Hop",
    "Niagara Falls (Foot or 2) [with Travis Scott & 21 Savage]": "Hip-Hop",
    "Eyes Closed": "Romantic",
    "Massive": "Hip-Hop",
    "Pass The Dutchie": "Hip-Hop",
    "IDGAF (with blackbear)": "Hip-Hop",
    "En Paris": "Hip-Hop",
    "Spin Bout U": "Hip-Hop",
    "DANCE CRIP": "Hip-Hop",
    "Limbo": "Hip-Hop",
    "Grapejuice": "Romantic",
    "Peso Pluma: Bzrp Music Sessions, Vol. 55": "Hip-Hop",
    "Less Than Zero": "Romantic",
    "Bar": "Hip-Hop",
    "Tattoo": "Romantic",
    "Static": "Rock",
    "Hati-Hati di Jalan": "Hip-Hop",
    "Thought You Should Know": "Rock",
    "The Astronaut": "Romantic",
    "When I R.I.P.": "Hip-Hop",
    "MIENTRAS ME CURO DEL CORA": "Hip-Hop",
    "Watch This - ARIZONATEARS Pluggnb Remix": "Romantic",
    "DANÇARINA": "Hip-Hop",
    "Sin Señal": "Hip-Hop",
    "Problemón": "Hip-Hop",
    "KICK BACK": "Hip-Hop",
    "Miracle (with Ellie Goulding)": "Romantic",
    "Polaroid Love": "Hip-Hop",
    "That That (prod. & feat. SUGA of BTS)": "Romantic",
    "MANIAC": "Hip-Hop",
    "El Apagón": "Hip-Hop",
    "WORTH NOTHING": "Romantic",
    "POP!": "Hip-Hop",
    "Cupido": "Hip-Hop",
    "Mastermind": "Romantic",
    "Bad Decisions (with BTS & Snoop Dogg)": "Romantic",
    "PLAYA DEL INGLÉS": "Hip-Hop",
    "Betty (Get Money)": "Romantic",
    "KU LO SA - A COLORS SHOW": "Hip-Hop",
    "Eu Gosto Assim - Ao Vivo": "Hip-Hop",
    "Question...?": "Romantic",
    "Se Le Ve": "Hip-Hop",
    "Marisola - Remix": "Romantic",
    "El Merengue": "Hip-Hop",
    "THE LONELIEST": "Romantic",
    "I AM WOMAN": "Romantic",
    "When I’m Gone (with Katy Perry)": "Romantic",
    "Evergreen (You Didn’t Deserve Me At All)": "Romantic",
    "Starlight": "Romantic",
    "FEARLESS": "Rock",
    "MERCHO": "Hip-Hop",
    "SUPERMODEL": "Romantic",
    "Mujeriego": "Hip-Hop",
    "FLOWER": "Romantic",
    "Love Of My Life": "Romantic",
    "Nosso Quadro": "Hip-Hop",
    "Typa Girl": "Hip-Hop",
    "Keep Driving": "Romantic",
    "Quê Será?": "Hip-Hop",
    "Tom's Diner": "Romantic",
    "Entre Nosotros (Remix) [con Nicki Nicole]": "Hip-Hop",
    "Die Hard": "Hip-Hop",
    "Hold My Hand": "Romantic",
    "Forget Me": "Romantic",
    "With you": "Romantic",
    "Plan A": "Hip-Hop",
    "Malvadísimx": "Hip-Hop",
    "Ginseng Strip 2002": "Hip-Hop",
    "Don't You Worry": "Hip-Hop",
    "Christmas (Baby Please Come Home)": "Romantic",
    "B.O.T.A. (Baddest Of Them All) - Edit": "Hip-Hop",
    "Heart To Heart": "Romantic",
    "Thousand Miles": "Romantic",
    "Afraid To Feel": "Romantic",
    "San Lucas": "Hip-Hop",
    "THE SHADE": "Romantic",
    "TO THE MOON": "Hip-Hop",
    "Run Rudolph Run - Single Version": "Romantic",
    "Cayó La Noche (feat. Cruz Cafuné, Abhir Hathi, Bejo, EL IMA)": "Hip-Hop",
    "Agosto": "Hip-Hop",
    "Stay Alive (Prod. SUGA of BTS)": "Hip-Hop",
    "Die For You": "Hip-Hop",
    "2 Be Loved (Am I Ready)": "Romantic",
    "ELEVEN": "Hip-Hop",
    "Rara Vez": "Hip-Hop",
    "Villano Antillano: Bzrp Music Sessions, Vol. 51": "Hip-Hop",
    "Coco Chanel": "Hip-Hop",
    "Down Under (feat. Colin Hay)": "Hip-Hop",
    "Vigilante Shit": "Hip-Hop",
    "PUFFIN ON ZOOTIEZ": "Hip-Hop",
    "When You're Gone": "Romantic",
    "El Gordo Trae El Mando": "Hip-Hop",
    "Moonlight": "Romantic",
    "Esqueça-Me Se For Capaz": "Hip-Hop",
    "Numb Little Bug": "Romantic",
    "My Only Wish (This Year)": "Romantic",
    "Peru": "Hip-Hop",
    "Salimo de Noche": "Hip-Hop",
    "Ojos Marrones": "Hip-Hop",
    "Bombonzinho - Ao Vivo": "Hip-Hop",
    "Mon Amour - Remix": "Hip-Hop",
    "Vai Lá Em Casa Hoje": "Hip-Hop",
    "Attention": "Hip-Hop",
    "After LIKE": "Hip-Hop",
    "Car's Outside": "Hip-Hop",
    "X SI VOLVEMOS": "Hip-Hop",
    "Surface Pressure": "Romantic",
    "Levitating": "Hip-Hop",
    "Cooped Up (with Roddy Ricch)": "Hip-Hop",
    "Low": "Hip-Hop",
    "Pantysito": "Hip-Hop",
    "Little Freak": "Romantic",
    "Caile": "Hip-Hop",
    "Trance (with Travis Scott & Young Thug)": "Hip-Hop",
    "BILLIE EILISH.": "Hip-Hop",
    "Ferxxo 100": "Hip-Hop",
    "ULTRA SOLO REMIX": "Hip-Hop",
    "Enséñame A Bailar": "Hip-Hop",
    "Forever": "Hip-Hop",
    "Un Verano Sin Ti": "Hip-Hop",
    "Aguacero": "Hip-Hop",
    "Hold Me Closer": "Romantic",
    "Pasoori": "Hip-Hop",
    "How Do I Say Goodbye": "Hip-Hop",
    "Radio": "Hip-Hop",
    "Nobody Gets Me": "Hip-Hop",
    "Too Many Nights (feat. Don Toliver & with Future)": "Hip-Hop",
    "Crazy What Love Can Do": "Hip-Hop",
    "It'll Be Okay": "Hip-Hop",
    "El Rescate": "Hip-Hop",
    "Ch y la Pizza": "Hip-Hop",
    "Every Summertime": "Romantic",
    "Daylight": "Hip-Hop",
    "Mal Feito - Ao Vivo": "Hip-Hop",
    "ceilings": "Romantic",
    "Last Last": "Hip-Hop",
    "CAIRO": "Hip-Hop",
    "Siempre Pendientes": "Hip-Hop",
    "Numb": "Romantic",
    "It's Beginning to Look a Lot Like Christmas (with Mitchell Ayres & His Orchestra)": "Rock",
    "Lift Me Up - From Black Panther: Wakanda Forever - Music From and Inspired By": "Romantic",
    "LET GO": "Hip-Hop",
    "Sweetest Pie": "Romantic",
    "Chale": "Hip-Hop",
    "Where Did You Go?": "Hip-Hop",
    "ANTIFRAGILE": "Romantic",
    "N95": "Rock",
    "SPIT IN MY FACE!": "Hip-Hop",
    "Yet To Come": "Romantic",
    "SPIT IN MY FACE!": "Hip-Hop",
    "WHERE SHE GOES": "Hip-Hop",
    "PUNTO 40": "Hip-Hop",
    "Gato de Noche": "Hip-Hop",
    "Me Fui de Vacaciones": "Hip-Hop",
    "LOVE DIVE": "Romantic",
    "Fin de Semana": "Hip-Hop",
    "ULTRA SOLO": "Hip-Hop",
    "Besos Moja2": "Hip-Hop",
    "Shirt": "Hip-Hop",
    "pushin P (feat. Young Thug)": "Hip-Hop",
    "Satellite": "Romantic",
    "La Zona": "Hip-Hop",
    "Yo No Soy Celoso": "Hip-Hop",
    "Christmas Tree": "Romantic",
    "Maroon": "Romantic",
    "Otro Atardecer": "Hip-Hop",
    "Maan Meri Jaan": "Romantic",
    "Ya No Somos Ni Seremos": "Hip-Hop",
    "GATĂÂ": "Hip-Hop",
    "Dreamers [Music from the FIFA World Cup Qatar 2022 Official Soundtrack]": "Hip-Hop",
    "Snow On The Beach (feat. Lana Del Rey)": "Romantic",
    "JGL": "Hip-Hop",
    "10:35": "Hip-Hop",
    "Sacrifice": "Hip-Hop",
    "Excuses": "Hip-Hop",
    "Bejeweled": "Hip-Hop",
    "Por las Noches": "Hip-Hop",
    "Run BTS": "Hip-Hop",
    "cĂÂmo dormi": "Hip-Hop",
    "STAR WALKIN' (League of Legends Worlds Anthem)": "Hip-Hop",
    "La Llevo Al Cielo (Ft. ĂÂengo F": "Hip-Hop",
    "Music For a Sushi Restaurant": "Hip-Hop",
    "Players": "Hip-Hop",
    "Classy 101": "Hip-Hop",
    "Dos Mil 16": "Hip-Hop",
    "TV": "Romantic",
    "Demasiadas Mujeres": "Hip-Hop",
    "Out of Time": "Romantic",
    "Super Gremlin": "Hip-Hop",
    "Nonsense": "Hip-Hop",
    "she's all i wanna be": "Hip-Hop",
    "Andrea": "Hip-Hop",
    "CHORRITO PA LAS ANIMAS": "Hip-Hop",
    "The Feels": "Hip-Hop",
    "this is what falling in love feels like": "Romantic",
    "You're On Your Own, Kid": "Romantic",
    "Fingers Crossed": "Hip-Hop",
    "X ĂÂLTIMA": "Hip-Hop",
    "You Belong With Me (TaylorĂÂĂÂs Ve": "Romantic",
    "Merry Christmas Everyone": "Romantic",
    "Sad Girlz Luv Money Remix (feat. Kali Uchis)": "Hip-Hop",
    "El Azul": "Hip-Hop",
    "BREAK MY SOUL": "Hip-Hop",
    "Ley Seca": "Hip-Hop",
    "I Hate U": "Hip-Hop",
    "METAMORPHOSIS": "Hip-Hop",
    "BESO": "Hip-Hop",
    "Vista Al Mar": "Hip-Hop",
    "Like Crazy": "Hip-Hop",
    "Acapulco": "Hip-Hop",
    "Hype Boy": "Hip-Hop",
    "Matilda": "Romantic",
    "Kesariya (From 'Brahmastra')": "Romantic",
    "Bebe Dame": "Hip-Hop",
    "You Proof": "Hip-Hop",
    "Something In The Way - Remastered 2021": "Hip-Hop",
    "Alien Blues": "Hip-Hop",
    "Bloody Mary": "Hip-Hop",
    "People": "Hip-Hop",
    "Tiago PZK: Bzrp Music Sessions, Vol. 48": "Hip-Hop",
    "LA FAMA (with The Weeknd)": "Hip-Hop",
    "Praise God": "Hip-Hop",
    "Selfish": "Hip-Hop",
    "MonotonĂÂ": "Hip-Hop",
    "Punto G": "Hip-Hop",
    "In The Stars": "Romantic",
    "Smokin Out The Window": "Hip-Hop",
    "Belly Dancer": "Hip-Hop",
    "Mary On A Cross": "Hip-Hop",
    "Daylight": "Hip-Hop",
    "The Christmas Song (Merry Christmas To You) - Remastered 1999": "Romantic",
    "Is There Someone Else?": "Hip-Hop",
    "Medallo": "Hip-Hop",
    "Jordan": "Hip-Hop",
    "A Holly Jolly Christmas - Single Version": "Romantic",
    "White Christmas": "Romantic",
    "Ditto": "Hip-Hop",
    "Snooze": "Hip-Hop",
    "Superhero (Heroes & Villains) [with Future & Chris Brown]": "Hip-Hop",
    "ĂÂĂÂĂÂĂÂĂÂĂÂĂÂĂÂĂÂĂÂ": "Hip-Hop",
    "Un Coco": "Hip-Hop",
    "Wonderful Christmastime - Edited Version / Remastered 2011": "Romantic",
    "Karma": "Hip-Hop",
    "Sleigh Ride": "Romantic",
    "No Se Va": "Hip-Hop",
    "Shut up My Moms Calling": "Rock",
    "Angel Baby": "Romantic",
    "Those Eyes": "Romantic",
    "Happier Than Ever - Edit": "Romantic",
    "The Color Violet": "Hip-Hop",
    "Un Ratito": "Hip-Hop",
    "Better Days (NEIKED x Mae Muller x Polo G)": "Hip-Hop",
    "Notion": "Hip-Hop",
    "Fuera del mercado": "Hip-Hop",
    "Thunder": "Hip-Hop",
        "All For Us - from the HBO Original Series Euphoria": "Hip-Hop",
    "OUT OUT (feat. Charli XCX & Saweetie)": "Hip-Hop",
    "Super Freaky Girl": "Hip-Hop",
    "Driving Home for Christmas - 2019 Remaster": "Romantic",
    "Last Night": "Hip-Hop",
    "OMG": "Hip-Hop",
    "Take My Breath": "Romantic",
    "We Don't Talk About Bruno": "Hip-Hop",
    "Midnight Rain": "Romantic",
    "PRC": "Hip-Hop",
    "Nostálgía": "Hip-Hop",
    "Me and Your Mama": "Hip-Hop",
    "Calm Down": "Hip-Hop",
    "Let It Snow! Let It Snow! Let It Snow!": "Romantic",
    "Vegas (From the Original Motion Picture Soundtrack ELVIS)": "Hip-Hop",
    "Murder In My Mind": "Hip-Hop",
    "Something in the Orange": "Romantic",
    "Just Wanna Rock": "Hip-Hop",
    "Normal": "Hip-Hop",
    "Happy Xmas (War Is Over)": "Romantic",
    "NEW MAGIC WAND": "Hip-Hop",
    "Después de la P": "Hip-Hop",
    "Ferrari": "Hip-Hop",
    "AMG": "Hip-Hop",
    "Cállate Tú": "Hip-Hop",
    "Oh My God": "Hip-Hop",
    "Lovers Rock": "Hip-Hop",
    "Mount Everest": "Hip-Hop",
    "LOKERA": "Hip-Hop",
    "Let It Snow! Let It Snow! Let It Snow!": "Romantic",
    "Holly Jolly Christmas": "Romantic",
    "LA INOCENTE": "Hip-Hop",
    "La Corriente": "Hip-Hop",
    "Sex, Drugs, Etc.": "Hip-Hop",
    "Do They Know It's Christmas? - 1984 Version": "Romantic",
    "Shut Down": "Hip-Hop",
    "Doja": "Hip-Hop",
    "Underneath the Tree": "Romantic",
    "Lavender Haze": "Romantic",
    "Way 2 Sexy (with Future & Young Thug)": "Hip-Hop",
    "Boyfriend": "Hip-Hop",
    "Cupid - Twin Ver.": "Hip-Hop",
    "Miss You": "Hip-Hop",
    "Swim": "Hip-Hop",
    "Ain't Shit": "Hip-Hop",
    "Light Switch": "Hip-Hop",
    "Life Goes On": "Hip-Hop",
    "Made You Look": "Hip-Hop",
    "un x100to": "Hip-Hop",
    "Sky": "Hip-Hop",
    "Tacones Rojos": "Hip-Hop",
    "Sobrio": "Hip-Hop",
    "Get Into It (Yuh)": "Hip-Hop",
    "Die For You - Remix": "Hip-Hop",
    "Feliz Navidad": "Romantic",
    "Yo Voy (feat. Daddy Yankee)": "Hip-Hop",
    "AM Remix": "Hip-Hop",
    "Meet Me At Our Spot": "Rock",
    "Escapism.": "Hip-Hop",
    "La Jumpa": "Hip-Hop",
    "One Right Now (with The Weeknd)": "Hip-Hop",
    "Love Nwantiti - Remix": "Hip-Hop",
    "Es un Secreto": "Hip-Hop",
    "Envolver": "Hip-Hop",
    "Pink Venom": "Hip-Hop",
    "La Bebe - Remix": "Hip-Hop",
    "Formula": "Hip-Hop",
    "WAIT FOR U (feat. Drake & Tems)": "Hip-Hop",
    "family ties (with Kendrick Lamar)": "Hip-Hop",
    "Still Don't Know My Name": "Hip-Hop",
    "Don't Be Shy": "Hip-Hop",
    "Angels Like You": "Romantic",
    "Atlantis": "Hip-Hop",
    "Rich Flex": "Hip-Hop",
    "Mon Amour - Remix": "Hip-Hop",
    "California Love - Original Version (Explicit)": "Hip-Hop",
    "House Of Memories": "Hip-Hop",
    "Toxic": "Hip-Hop",
    "All Too Well (10 Minute Version) (Taylor's Version) (From The Vault)": "Romantic",
    "Yandel 150": "Hip-Hop",
    "Only Love Can Hurt Like This": "Romantic",
    "Fair Trade (with Travis Scott)": "Hip-Hop",
    "Knife Talk (with 21 Savage ft. Project Pat)": "Hip-Hop",
    "CUFF IT": "Hip-Hop",
    "Miénteme": "Hip-Hop",
    "Softcore": "Hip-Hop",
    "Until I Found You (with Em Beihold) - Em Beihold Version": "Romantic",
    "Feliz Cumpleaños Ferxxo": "Hip-Hop",
    "Te Felicito": "Hip-Hop",
    "august": "Romantic",
    "Tarot": "Hip-Hop",
    "Permission to Dance": "Hip-Hop",
    "I Like You (A Happier Song) (with Doja Cat)": "Hip-Hop",
    "Volando - Remix": "Hip-Hop",
    "Stargirl Interlude": "Hip-Hop",
    "Moth To A Flame (with The Weeknd)": "Hip-Hop",
    "Party": "Hip-Hop",
    "Jimmy Cooks (feat. 21 Savage)": "Hip-Hop",
    "TQG": "Hip-Hop",
    "Enchanted": "Romantic",
    "Sparks": "Romantic",
    "2055": "Hip-Hop",
    "Mistletoe": "Romantic",
    "Here With Me": "Romantic",
    "After Dark": "Hip-Hop",
    "Leave Before You Love Me (with Jonas Brothers)": "Romantic",
    "Sunroof": "Romantic",
    "Superman": "Hip-Hop",
    "The Motto": "Hip-Hop",
    "Gasolina": "Hip-Hop",
    "It's the Most Wonderful Time of the Year": "Romantic",
    "jealousy, jealousy": "Hip-Hop",
    "Neverita": "Hip-Hop",
    "You Right": "Hip-Hop",
    "Volví": "Hip-Hop",
    "Hey Mor": "Hip-Hop",
    "Do It To It": "Hip-Hop",
    "Forgot About Dre": "Hip-Hop",
    "Cool for the Summer": "Hip-Hop",
    "Romantic Homicide": "Hip-Hop",
    "Una Noche en Medellín": "Hip-Hop",
    "Reminder": "Hip-Hop",
    "Don't Blame Me": "Romantic",
    "A Tu Merced": "Hip-Hop",
    "Lost in the Fire": "Hip-Hop",
    "Snowman": "Romantic",
    "First Class": "Hip-Hop",
    "After Hours": "Romantic",
    "Bound 2": "Hip-Hop",
    "Master of Puppets (Remastered)": "Rock",
    "I Was Never There": "Romantic",
    "SNAP": "Romantic",
    "MAMIII": "Hip-Hop",
    "Left and Right (Feat. Jung Kook of BTS)": "Romantic",
    "Qué Más Pues?": "Hip-Hop",
    "Shakira: Bzrp Music Sessions, Vol. 53": "Hip-Hop",
    "we fell in love in october": "Romantic",
    "About Damn Time": "Hip-Hop",
    "Ella Baila Sola": "Hip-Hop",
    "Until I Found You": "Romantic",
    "love nwantiti (ah ah ah)": "Hip-Hop",
    "Jingle Bell Rock": "Romantic",
    "Late Night Talking": "Romantic",
    "golden hour": "Romantic",
    "Bam Bam (feat. Ed Sheeran)": "Romantic",
    "La Santa": "Hip-Hop",
    "Rockin' Around The Christmas Tree": "Romantic",
    "Lo Siento BB:/ (with Bad Bunny & Julieta Venegas)": "Hip-Hop",
    "Bored": "Hip-Hop",
    "DESPECHÁ": "Hip-Hop",
    "favorite crime": "Romantic",
    "Style": "Romantic",
    "Space Song": "Rock",
    "Levitating": "Romantic",
    "RAPSTAR": "Hip-Hop",
    "Cruel Summer": "Romantic",
    "Pink + White": "Hip-Hop",
    "Golden": "Romantic",
    "It's Beginning To Look A Lot Like Christmas": "Romantic",
    "Desesperados": "Hip-Hop",
    "cardigan": "Romantic",
    "Lost": "Romantic",
    "Bad Habit": "Hip-Hop",
    "Freaks": "Hip-Hop",
    "Good Days": "Hip-Hop",
    "Santa Tell Me": "Romantic",
    "Bones": "Rock",
    "Dream On": "Rock",
    "Apocalypse": "Rock",
    "The Next Episode": "Hip-Hop",
    "Creepin'": "Hip-Hop",
    "happier": "Romantic",
    "I WANNA BE YOUR SLAVE": "Hip-Hop",
    "MONEY": "Hip-Hop",
    "Friday (feat. Mufasa & Hypeman) - Dopamine Re-Edit": "Hip-Hop",
    "Streets": "Hip-Hop",
    "MIDDLE OF THE NIGHT": "Hip-Hop",
    "Lover": "Romantic",
    "PROVENZA": "Hip-Hop",
    "Heartless": "Hip-Hop",
    "Infinity": "Romantic",
    "Calm Down (with Selena Gomez)": "Hip-Hop",
    "Moscow Mule": "Hip-Hop",
    "Stan": "Hip-Hop",
    "Dark Red": "Hip-Hop",
    "THATS WHAT I WANT": "Hip-Hop",
    "Wait a Minute!": "Hip-Hop",
    "Under The Influence": "Hip-Hop",
    "Get Lucky - Radio Edit": "Romantic",
    "Unstoppable": "Romantic",
    "Sure Thing": "Romantic",
    "HEARTBREAK ANNIVERSARY": "Romantic",
    "No Lie": "Hip-Hop",
    "I Love You So": "Romantic",
    "Where Are You Now": "Hip-Hop",
    "Summertime Sadness": "Romantic",
    "Glimpse of Us": "Romantic",
    "Arcade": "Romantic",
        "Anti-Hero": "Hip-Hop",
    "abcdefu": "Hip-Hop",
    "Revenge": "Hip-Hop",
    "Falling": "Romantic",
    "Running Up That Hill (A Deal With God)": "Rock",
    "Need To Know": "Hip-Hop",
    "See You Again": "Hip-Hop",
    "Efecto": "Hip-Hop",
    "Happier Than Ever": "Hip-Hop",
    "My Universe": "Romantic",
    "The Business": "Romantic",
    "Talking To The Moon": "Romantic",
    "Boy With Luv (feat. Halsey)": "Romantic",
    "I Ain't Worried": "Hip-Hop",
    "Somewhere Only We Know": "Romantic",
    "Money Trees": "Hip-Hop",
    "I'm Good (Blue)": "Hip-Hop",
    "Shake It Off": "Hip-Hop",
    "Leave The Door Open": "Romantic",
    "Dandelions": "Romantic",
    "SLOW DANCING IN THE DARK": "Romantic",
    "Daddy Issues": "Hip-Hop",
    "Night Changes": "Romantic",
    "Ojitos Lindos": "Hip-Hop",
    "Astronaut In The Ocean": "Hip-Hop",
    "Butter": "Hip-Hop",
    "Have You Ever Seen The Rain?": "Rock",
    "Last Christmas": "Romantic",
    "Kill Bill": "Hip-Hop",
    "Set Fire to the Rain": "Romantic",
    "Ghost": "Romantic",
    "Todo De Ti": "Hip-Hop",
    "you broke me first": "Romantic",
    "Contection": "Hip-Hop",
    "Hope": "Hip-Hop",
    "In Da Club": "Hip-Hop",
    "Everybody Wants To Rule The World": "Rock",
    "Still D.R.E.": "Hip-Hop",
    "La Bachata": "Hip-Hop",
    "505": "Rock",
    "Save Your Tears (with Ariana Grande) (Remix)": "Romantic",
    "Enemy (with JID) - from the series Arcane League of Legends": "Hip-Hop",
    "Enemy - from the series Arcane League of Legends": "Hip-Hop",
    "Unholy (feat. Kim Petras)": "Hip-Hop",
    "traitor": "Romantic",
    "We Found Love": "Romantic",
    "Mockingbird": "Hip-Hop",
    "positions": "Romantic",
    "deja vu": "Romantic",
    "Yonaguni": "Hip-Hop",
    "Titi Me Preguntó": "Hip-Hop",
    "Why'd You Only Call Me When You're High?": "Rock",
    "Creep": "Rock",
    "Danza Kuduro": "Hip-Hop",
    "Iris": "Romantic",
    "I Wanna Be Yours": "Rock",
    "Heather": "Romantic",
    "Shivers": "Romantic",
    "Callaita": "Hip-Hop",
    "Pepas": "Hip-Hop",
    "Flowers": "Romantic",
    "Woman": "Hip-Hop",
    "Blank Space": "Romantic",
    "Quevedo: Bzrp Music Sessions, Vol. 52": "Hip-Hop",
    "Gangsta's Paradise": "Hip-Hop",
    "Numb": "Rock",
    "Beggin": "Rock",
    "Let Me Down Slowly": "Romantic",
    "Easy On Me": "Romantic",
    "The Night We Met": "Romantic",
    "The Real Slim Shady": "Hip-Hop",
    "LA CANCIÓN": "Hip-Hop",
    "Adore You": "Romantic",
    "Me Porto Bonito": "Hip-Hop",
    "Peaches (feat. Daniel Caesar & Giveon)": "Romantic",
    "All I Want for Christmas Is You": "Romantic",
    "Call Out My Name": "Romantic",
    "The Nights": "Romantic",
    "Somebody That I Used To Know": "Romantic",
    "Rolling in the Deep": "Romantic",
    "Take On Me": "Rock",
    "Payphone": "Romantic",
    "Locked Out Of Heaven": "Romantic",
    "Sweet Child O' Mine": "Rock",
    "Bad Habits": "Romantic",
    "Kiss Me More (feat. SZA)": "Romantic",
    "Save Your Tears": "Romantic",
    "Viva La Vida": "Rock",
    "Every Breath You Take - Remastered 2003": "Rock",
    "Cold Heart - PNAU Remix": "Romantic",
    "I'm Not The Only One": "Romantic",
    "Before You Go": "Romantic",
    "The Scientist": "Rock",
    "In The End": "Rock",
    "Just The Way You Are": "Romantic",
    "Die For You": "Romantic",
    "When I Was Your Man": "Romantic",
    "Without Me": "Hip-Hop",
    "Smells Like Teen Spirit - Remastered 2021": "Rock",
    "Dynamite": "Hip-Hop",
        "'Till I Collapse": "Hip-Hop",
    "Mood (feat. Iann Dior)": "Hip-Hop",
    "There's Nothing Holdin' Me Back": "Romantic",
    "MONTERO (Call Me By Your Name)": "Hip-Hop",
    "Yellow": "Rock",
    "Memories": "Romantic",
    "Dakiti": "Hip-Hop",
    "Do I Wanna Know?": "Rock",
    "No Role Modelz": "Hip-Hop",
    "Levitating (feat. DaBaby)": "Romantic",
    "Mr. Brightside": "Rock",
    "Another Love": "Romantic",
    "INDUSTRY BABY (feat. Jack Harlow)": "Hip-Hop",
    "Lose Yourself - Soundtrack Version": "Hip-Hop",
    "Demons": "Rock",
    "drivers license": "Romantic",
    "good 4 u": "Romantic",
    "One Kiss (with Dua Lipa)": "Romantic",
    "HUMBLE.": "Hip-Hop",
    "The Hills": "Hip-Hop",
    "Can't Hold Us (feat. Ray Dalton)": "Hip-Hop",
    "Wake Me Up - Radio Edit": "Romantic",
    "Riptide": "Romantic",
    "Counting Stars": "Rock",
    "All of Me": "Romantic",
    "Love Yourself": "Romantic",
    "Circles": "Romantic",
    "Take Me To Church": "Rock",
    "Shallow": "Romantic",
    "Bohemian Rhapsody - Remastered 2011": "Rock",
    "Something Just Like This": "Romantic",
    "Photograph": "Romantic",
    "Thinking Out Loud": "Romantic",
    "Sweater Weather": "Romantic",
    "Lucid Dreams": "Hip-Hop",
    "Don't Start Now": "Romantic",
    "Watermelon Sugar": "Romantic",
    "lovely - Bonus Track": "Romantic",
    "Say You Won't Let Go": "Romantic",
    "Señorita": "Romantic",
    "As It Was": "Romantic",
    "Heat Waves": "Romantic",
    "Perfect": "Romantic",
    "Starboy": "Hip-Hop",
    "Closer": "Romantic",
    "Believer": "Rock",
    "STAY (with Justin Bieber)": "Romantic",
    "One Dance": "Hip-Hop",
    "Sunflower - Spider-Man: Into the Spider-Verse": "Hip-Hop",
    "Dance Monkey": "Romantic",
    "Someone You Loved": "Romantic",
    "Shape of You": "Romantic",
    "Blinding Lights": "Hip-Hop"
}

# Update the genre column based on the track name
spotify_df['Genre'] = spotify_df['track_name'].map(genre_dict)

output_file_name = 'spotify-2023-updated2.csv'

# Get the directory of the original file
output_directory = os.path.dirname(file_path)

# Construct the output file path
output_file_path = os.path.join(output_directory, output_file_name)

# Save the updated DataFrame to CSV
spotify_df.to_csv(output_file_path, index=False)

print("Data saved to:", output_file_path)

